Il93/mobile display heart rate
isakk7/EVAT_frontend pull request #11
Opened 2023-01-25 18:36 UTC by rafael-ramirez-orte

# Description

Please include a short summary of the change and which issue is fixed.

### Screenshots, Videos, Gifs.
![WhatsApp Image 2023-01-25 at 12 35 40 PM](https://user-images.githubusercontent.com/74692412/214652537-9a5adb63-48d2-4245-8746-e8f479292357.jpeg)

Add some screenshots, videos, gifs, etc, that may help the reviewer to get a better context of the requested changes.

# Checklist:

- [ ] Pull request owner assigned
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have pulled / merged main/develop into this branch

[IL-ID]

2023-01-25 18:48 UTC, JavierRuvalcaba requested changes

2023-01-25 18:48 UTC, JavierRuvalcaba commented on page/DailyForm.jsx
> +	console.log(watch("FC"))
Remove console log

2023-01-25 18:48 UTC, JavierRuvalcaba commented on page/DailyForm.jsx
> +		console.log(data, selectedValue);
Remove console log

2023-01-25 18:48 UTC, JavierRuvalcaba commented on page/DailyForm.jsx
> +        console.log(control._fields.resp,watch("resp"))
remove console log

2023-01-25 18:48 UTC, JavierRuvalcaba commented on page/DailyForm.jsx
> +        console.log(control._fields.resp,watch("cardio"))
remove console log

2023-01-25 18:48 UTC, JavierRuvalcaba commented on page/DailyForm.jsx
> +							placeholder="Preocupacion enfermera"
```suggestion
							placeholder="Preocupación enfermera"
```

2023-01-25 18:48 UTC, JavierRuvalcaba commented on page/DailyForm.jsx
> +							placeholder="Preocupacion familia"
```suggestion
							placeholder="Preocupación familia"
```

2023-01-25 19:03 UTC, JavierRuvalcaba approved these changes

2023-01-26 15:35 UTC, pedro123-67we approved these changes
muy bien!!!

2023-01-26 15:36 UTC, merged