Il 53/login
isakk7/EVAT_frontend pull request #2
Opened 2022-12-13 17:11 UTC by isakk7

# Description

Login was connected to the back with auth working, design the login

![IMG_F7FE4BB42C05-1](https://user-images.githubusercontent.com/74216113/207399173-903bd711-f24d-4ba5-bc89-a1579d51ec9a.jpeg)

# Checklist:

- [ ] Pull request owner assigned
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have pulled / merged main/develop into this branch

[IL-53]

2022-12-13 18:00 UTC, JavierRuvalcaba requested changes

2022-12-13 18:00 UTC, JavierRuvalcaba commented on App.js
> +
remove this line

2022-12-13 18:00 UTC, JavierRuvalcaba commented on components/Boton.jsx
> +                Ingresa
What is the `{text}` variable use for?

2022-12-13 18:00 UTC, JavierRuvalcaba commented on components/Boton.jsx
> +                Ingresa
The name of the file has a typo.   It should be `Button`

2022-12-13 18:00 UTC, JavierRuvalcaba commented on hooks/useFetch.js
> +export default useFetch;
Maybe, this file will cause merge issues with the one in the @rafael-ramirez-orte 's PR

2022-12-13 18:00 UTC, JavierRuvalcaba commented on page/Login.jsx
> +
Why this file has only import statements?

2022-12-13 18:00 UTC, JavierRuvalcaba commented on page/LoginPage.jsx
> +  return (
```suggestion
  const { loginRequest } = useFetch();
  
  const onSubmit = async (data) => {
    try {
      navigation.navigate("PatientRegister");
    } catch (err) {
      console.log(err);
    }
  };
  
  return (
```

2022-12-13 18:00 UTC, JavierRuvalcaba commented on page/LoginPage.jsx
> +  input: {
```suggestion
  );
};

const styles = StyleSheet.create({
  input: {
```

2022-12-13 19:01 UTC, JavierRuvalcaba approved these changes

2022-12-14 15:34 UTC, pedro123-67we approved these changes

2022-12-14 15:36 UTC, pedro123-67we approved these changes

2022-12-14 15:36 UTC, merged