Feat:Completed patient form
isakk7/EVAT_frontend pull request #3
Opened 2022-12-13 17:13 UTC by rafael-ramirez-orte

# Description

Implementation of an alert, form refresh and connection to the backend was done. 

### Screenshots, Videos, Gifs.

![image](https://user-images.githubusercontent.com/74692412/207399295-47790dd3-2222-4f41-9c1d-49d915e0db67.png)

# Checklist:

- [ ] Pull request owner assigned
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have pulled / merged main/develop into this branch

[IL-52]

2022-12-13 17:48 UTC, JavierRuvalcaba requested changes

2022-12-13 17:48 UTC, JavierRuvalcaba commented on navigation/MainStack.jsx
> +
remove the blank spaces

2022-12-13 17:48 UTC, JavierRuvalcaba commented on navigation/MainStack.jsx
>  )
fix the indentation

2022-12-13 17:48 UTC, JavierRuvalcaba commented on page/LoginPage.jsx
> +
remove the blank space and fix the indentation for the Button component

2022-12-13 17:48 UTC, JavierRuvalcaba commented on page/PatientRegisterPage.jsx
> +    console.log(data);
remove this console.log

2022-12-13 17:48 UTC, JavierRuvalcaba commented on page/PatientRegisterPage.jsx
> +  const onSubmit = async (data) => {
```suggestion
  const {
    control,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm();
  
  const cleanForm = () => {
    setValue("name", "");
    setValue("typeOfCancer", "");
    setValue("services", "");
    setValue("palliative", "");
    setValue("age", "");
  };
  
  const { patientRequest } = useFetch();
  
  const onSubmit = async (data) => {
```

2022-12-13 18:40 UTC, JavierRuvalcaba approved these changes

2022-12-14 18:42 UTC, isakk7 approved these changes

2022-12-14 18:47 UTC, merged